### ISSUE TITLE
Solution to excersise 3.4 is not correct.

### ISSUE THREAD

**Issue by half-cto** [angelsolaorbaiceta/fe-fwk-book#224]
`<p>` element missing in solution of exercise 3.4

**To Reproduce**
Provided solution (below), returns text node directly inside <div>

```
function MessageComponent({ level, message }) {
  return h('div', { class: `message message--${level}` }, [message])
}
```

**Expected behavior**
Text node should be returned inside `<p>` that's inside `<div>`
(markup from book)

```
<div class="message message--info">
  <p>This is an info message</p>
</div>
```

**Solution**
here is MessageComponent() that returns expected virtual DOM

```
MessageComponent({ level, message }) {
    return h('div', { class: `message message--${level}` }, [
        h('p', {}, [message]),
    ]);
}
```

**Comment by angelsolaorbaiceta** [comment]
Hi @half-cto, you are completely right.

I [fixed the solution](https://github.com/angelsolaorbaiceta/fe-fwk-book/wiki/Solution-to-exercises#exercise-34) in the Wiki. Thanks a lot for writing such a detailed description, and for the feedback.

Best,
Angel
