### ISSUE TITLE
The arraysDiff function might be failed in some special cases.

### ISSUE THREAD

**Issue by terrence-ou** [angelsolaorbaiceta/fe-fwk-book#260]
Above all, thanks so much for such an awesome book! I got it last week and keep reading it every day and practicing the implementations!

**Describe the bug**
When I was writing additional test cases for the `arraysDiff` function in package/runtime/src/utils/arrays.js, I found the test will be failed in the following case:
```
  it("array items removed", () => {
    const oldArr = [1, 1, 2, 2, 3, 4, 5];
    const newArr = [1, 2, 3, 4, 5];
    const { added, removed } = arraysDiff(oldArr, newArr);
    expect(added).toEqual([]);
    expect(removed).toEqual([1, 2]); // this case failed
  });
```
The expected removed result is [1, 2], but the actual output is [].
I feel the current code has a bit difficulty handling duplicated items.

**To Reproduce**
1. Go to './package/runtime/src/__tests__/arrays.test.js'
2. Add a test case listed above
3. Run `npm run test` in the `runtime` folder

**Expected behavior**
The output of the function based on the above test case is expected be [1, 2]

**Comment by angelsolaorbaiceta** [comment]
Hi @terrence-ou , thanks for reporting this. I will take a look as soon as I find some time.

**Comment by terrence-ou** [comment]
Hi @angelsolaorbaiceta, I have some follow-ups to this issue. I think the issue will not affect the reconciliation process, because this function is only been used in `patchClasses(el, oldClass, newClass)` so far; the document API will automatically remove the duplicated classnames, therefore duplication in the array is never a matter in this scenario.

**Comment by angelsolaorbaiceta** [comment]
Hi @terrence-ou , this is a very interesting discovery! I see what happens here: I never considered duplicates for this function. As you say, I never found out because it has no effect in the reconciliation of CSS classes, but's conceptually wrongly implemented.

We need a new algorithm which deals with duplicates, that can figure out that from `[1, 1]` to `[1]` one `1` was removed. I'll think about possible ways of fixing this. 

Thanks for following up!

**Comment by angelsolaorbaiceta** [comment]
I think I found a solution (at least it works in my mind). I'll try to find some time to implement it and show you for a second opinion @terrence-ou . Thanks for bringing this to my attention; very interesting problem indeed.

**Comment by angelsolaorbaiceta** [comment]
Hey @terrence-ou I implemented a different algorithm that takes into account how many times each item appears in the arrays.
You can check it in PR #263 . 
Let me know what you think about the solution and if you can think of cases were it could break.

Thanks a lot for your time and dedication! Super appreciated.
