### ISSUE TITLE
"npx fe-fwk init my-framework-name" failed with npm "ERR! could not determine executable to run"

### ISSUE THREAD

**Issue by Onlinee** [angelsolaorbaiceta/fe-fwk-book#66]
Hello Angel,

if i try to initialize my project with npx as recomended i get this error :

$ npx fe-fwk init 2023-fe-fwk-npx 
npm ERR! could not determine executable to run
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/onlinee/.npm/_logs/2023-03-12T13_34_59_359Z-debug-0.log

Here is my log file:

0 verbose cli /home/onlinee/.nvm/versions/node/v18.15.0/bin/node /home/onlinee/.nvm/versions/node/v18.15.0/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/onlinee/.nvm/versions/node/v18.15.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/onlinee/source/manning/frontend-web-from-scratch/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/onlinee/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/onlinee/.nvm/versions/node/v18.15.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec fe-fwk init 2023-fe-fwk-npx
21 verbose argv "exec" "fe-fwk" "init" "2023-fe-fwk-npx"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/onlinee/.npm/_logs/2023-03-12T13_20_02_219Z-
26 verbose logfile /home/onlinee/.npm/_logs/2023-03-12T13_20_02_219Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 13ms
31 silly logfile start cleaning logs, removing 2 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 http fetch GET 200 https://registry.npmjs.org/fe-fwk 828ms (cache revalidated)
35 timing command:exec Completed in 841ms
36 verbose stack **Error: could not determine executable to run**
36 verbose stack     at getBinFromManifest (/home/onlinee/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (/home/onlinee/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:185:15)
36 verbose stack     at async module.exports (/home/onlinee/.nvm/versions/node/v18.15.0/lib/node_modules/npm/lib/cli.js:134:5)
37 verbose pkgid fe-fwk@2.0.1
38 verbose cwd /home/onlinee/source/manning/frontend-web-from-scratch
39 verbose Linux 5.10.102.1-microsoft-standard-WSL2
40 verbose node v18.15.0
41 verbose npm  v9.5.0
42 error could not determine executable to run
43 verbose exit 1
44 timing npm Completed in 864ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /home/onlinee/.npm/_logs/2023-03-12T13_20_02_219Z-debug-0.log

Regards

**Comment by chris-c-thomas** [comment]
Yes agreed, @angelsolaorbaiceta - the scripts to allow a proper npx install for a empty project to work along with needs to be updated as right now it's not possible to use `npx` the way you normally would.

**Comment by angelsolaorbaiceta** [comment]
Hi @Onlinee and @chris-c-thomas , I will look into this.

**Comment by angelsolaorbaiceta** [comment]
Hey @Onlinee , could you try again now. I realized there's a typo in the book (which I'll correct ASAP). The `npx` command you need to run to create the project is:

```
npx fe-fwk-cli init <fwk-name>
```

Let me know if this works for you now.

**Comment by Onlinee** [comment]
Solved. It works for me.
