### ISSUE TITLE
Nested Fragments don't point to same parent.

### ISSUE THREAD

**Issue by jdkahn** [angelsolaorbaiceta/fe-fwk-book#77]
https://github.com/angelsolaorbaiceta/fe-fwk-book/blob/461894cb5f18b48f9788674d5ed3f38dd2540a83/packages/runtime/src/mount-dom.js#L120

If we have nested fragments, doesn't this result in the child `fragment.el` pointing to a fragment Node and not the original parent Node?

**Comment by angelsolaorbaiceta** [comment]
You were completely right, @jdkahn . Thanks for reporting this. As you can see in the attached PR, I wrote a test that reproduced the issue and fixed it.

**Comment by jdkahn** [comment]
@angelsolaorbaiceta With your fix the fragment now has no purpose and the children are mounted directly on the parent, which would result in worse performance as there would be more DOM manipulations (assuming the parent is already in the DOM). I think we'll need to either pass in a new param or walk up the parent tree to find the first non-fragment node. Another solution would be to allow `parentEl` to be either virtual DOM node or real DOM node.

**Comment by angelsolaorbaiceta** [comment]
You are right again. Let me think about this to find a solution, but I think what you suggest of walking up the hierarchy until a non-fragment is found is a good idea.

**Comment by angelsolaorbaiceta** [comment]
Hey @jdkahn , I thought about this for some time and played with several possible solutions. Bearing in mind that the objective of the code is to simple for everyone to understand it, I decided to finally get rid of native fragments. Please take a look at this PR #80 and let me know what you think.

**Comment by jdkahn** [comment]
Hey @angelsolaorbaiceta , PR looks good, and completely agree that the priority teaching the framework and not some complex logic to address the fragments. Also thanks for the doc reference about DocumentFragment.
